### ISSUE TITLE
使用自定义Controlbar后IsLive 值为true，仍会显示进度条

### ISSUE THREAD

**Issue by hxzpily2** [Chimeejs/chimee-plugin-controlbar#11]
children: {
                    play: {
                    },
                    progressTime: true,
                    progressBar: {
                        layout: 'top'
                    },
                    volume: {},
                  
                    screen: {}
                }

我的设置，我传入的islive 为true 但是controlbar的进度条仍显示，不自定义controlbar 没事

**Comment by yandeqiang** [comment]
没有配置的情况下， 会读默认的配置，这是会根据直播点播来获取配置。
https://github.com/Chimeejs/chimee-plugin-controlbar/blob/master/README.md#组件相关问题， 第一个问题
如果你配置好了 children 的话， 不管直播点播都是走你的配置。

**Comment by hxzpily2** [comment]
问题如果我的配置 在直播的情况下  我只传入
children: {
play: {}
volume: {},
screen: {}
  } 
因为没有隐藏的progressBar占位，导致play，volume ，screen 堆在一起了

**Comment by yandeqiang** [comment]
文档少写了一句。progressbar：false 就可以达到占位这个效果了。目前只有 progressbar 有这个功能。

**Comment by hxzpily2** [comment]
这个我没问题了，可以关闭了
