### ISSUE TITLE
在muted设置为true的时候，音量显示没有变化

### ISSUE THREAD

**Issue by hxzpily2** [Chimeejs/chimee-plugin-controlbar#12]
现在影响音量显示的 只有volume，但静音应该设置后音量应该归零才对

**Comment by hxzpily2** [comment]
这个并不影响项目开发，官方可以有时间后最后在修复

**Comment by toxic-johann** [comment]
音量显示指 volume ？？

muted 本身设置就不会影响 volume 。。

如果是 muted 本身设置后没有效果，这个就算 bug。

muted 后不能将 volume 设为 0，不然 muted 为 true 将 volume 设为 1？这不合理的，。

**Comment by toxic-johann** [comment]
原来是插件代码，@yandeqiang 如果要增加相关操作，也要思考相应问题。

**Comment by yandeqiang** [comment]
不过，这个在其他插件上也会有这样的歧义吧。 

这个操作： muted  = true 时候将 volume 致为 0  ，放在哪里比较好？

**Comment by toxic-johann** [comment]
这两个是不相关的。我建议用户就应该区分开。
