### ISSUE TITLE
updateClarity   清晰度列表更新的问题？

### ISSUE THREAD

**Issue by leadingGo** [Chimeejs/chimee-plugin-controlbar#21]
更新清晰度列表   具体怎样使用？可以写个例子吗？谢谢。。。。。。

**Comment by yandeqiang** [comment]
可以暴露一个方法去更新清晰度列表。

**Comment by leadingGo** [comment]
怎样暴漏呢？可以具体一些吗？谢谢。。。都写好了就差这一步更新不了

**Comment by yandeqiang** [comment]
我给你增加一下吧。

**Comment by leadingGo** [comment]
真的吗？太感谢了  不然我得愁死。。。

**Comment by leadingGo** [comment]
大神   加好了说一下，谢谢

**Comment by leadingGo** [comment]
updateClarity: function updateClarity(list) {
      if (!isArray$1(list)) {
        return console.error('list must be an array.');
      }
      this.children.clarity.initTextList(list);
    }
这个是不是暴漏的方法？

**Comment by yandeqiang** [comment]
是用这个方法。 看下 [readme]( https://github.com/Chimeejs/chimee-plugin-controlbar/blob/master/README.md#%E6%96%B9%E6%B3%95)

**Comment by leadingGo** [comment]
太感谢了   好了
