### ISSUE TITLE
npm install 失败

### ISSUE THREAD

**Issue by adjkldd** [Chimeejs/chimee-plugin-controlbar#24]
➜  chimee-plugin-controlbar git:(master) npm install
npm WARN deprecated postcss-cssnext@3.1.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
⸨            ░░░░░░⸩ ⠦ extract:chimee-helper: sill extract chimee-helper@git+https://github.com/Chimeejs/chimee-helper.git extracted to /Users/ldd/proj/web/chimee-plugin-controlbar/node_modules/.staging/
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to http://registry.npm.qiwoo.org/toxic-predicate-functions/download/toxic-predicate-functions-0.1.5.tgz failed, reason: **connect ETIMEDOUT 10.208.255.161:80**
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by toxic-johann** [comment]
@yandeqiang 似乎是谁用了 git 依赖的问题。然后还绑定了一个内源。检查一下 package-lock 是否发上去了。
