### ISSUE TITLE
icon: {} 设置svg路径不能显示

### ISSUE THREAD

**Issue by hxzpily2** [Chimeejs/chimee-plugin-controlbar#3]
我想设置自定义的图标
但是
这种方法并没有显示出来，图标全都丢失了
 icon: {
             small: './icon/screen-small.svg',
               full: './icon/screen-full.svg'
             }

插入svg 内容的方法可行
icon: {
            small: `
                   <svg width="32px" height="25px" viewBox="0 0 32 25" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <g stroke="none" stroke-width="1" fill="#ffffff" fill-rule="evenodd">
           。。。。。。

**Comment by yandeqiang** [comment]
路径设置， 目前只支持位图操作的。 你设置的这种方式， 应该把 svg 贴进去，而不是设置路径。
这么做的考虑是， 为了方便操作 svg 的颜色。如果是一张图的话， 就不容易操作了。
如果你非要使用这种方式的话， 可以设置 bitmap 为 true ,然后自己用 css background 设置路径就好了。

**Comment by huanshijie** [comment]
@yandeqiang 怎么把svg贴进去？
```javascript
icon: {
    pause: <svg>...</svg>,
    plan: <svg>...</svg>,
}
```
这样？我在react中引入的时候好像不生效

**Comment by yandeqiang** [comment]
字符串引入
