### ISSUE TITLE
控制器中的图标fill与stroke颜色控制

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee-plugin-controlbar#5]
建议控制条自带图标的fill与stroke硬编码到svg代码中，而非添加到css中来影响，此处可能出现的一个坑为，外部引入的svg图表被此处样式所影响

**Comment by yandeqiang** [comment]
这个 svg 的 css， 我默认的是全局可能有一个基色，再来一个 hover 颜色效果就够了。 所以在这全局设置了颜色，因此如果出现单一个特殊的 svg 时， 需要另写 css 去覆盖了。
这么做的假设是， 这个控制条上的图标样式（颜色／ 宽高），基本统一，所以这么搞。 如果这个后面证明假设不成立的话，确实就需要单个svg、有各自对应的 css 了。
